// Dummy Data based on Laravel Backend

export const users = [
  { id: 1, name: 'Admin Warehouse', email: 'admin@warehouse.com' },
  { id: 2, name: 'Budi Santoso', email: 'budi@warehouse.com' },
  { id: 3, name: 'Siti Nurhaliza', email: 'siti@warehouse.com' },
];

export const vendors = [
  {
    id: 1,
    name: 'PT. Elektronik Jaya',
    email: 'info@elektronikjaya.com',
    phone: '021-12345678',
    address: 'Jl. Sudirman No. 123, Jakarta Selatan',
    status: 'active',
    bank_name: 'Bank Mandiri',
    account_number: '1234567890',
    account_name: 'PT. Elektronik Jaya',
    payment_term: '30 hari',
    created_at: '2024-01-15',
  },
  {
    id: 2,
    name: 'CV. Maju Bersama',
    email: 'sales@majubersama.co.id',
    phone: '022-98765432',
    address: 'Jl. Asia Afrika No. 45, Bandung',
    status: 'active',
    bank_name: 'Bank BCA',
    account_number: '0987654321',
    account_name: 'CV. Maju Bersama',
    payment_term: '45 hari',
    created_at: '2024-02-20',
  },
  {
    id: 3,
    name: 'PT. Teknik Mandiri',
    email: 'contact@teknikmandiri.com',
    phone: '031-55667788',
    address: 'Jl. Raya Darmo No. 78, Surabaya',
    status: 'active',
    bank_name: 'Bank BRI',
    account_number: '5556667777',
    account_name: 'PT. Teknik Mandiri',
    payment_term: 'COD',
    created_at: '2024-03-10',
  },
  {
    id: 4,
    name: 'UD. Sumber Rezeki',
    email: 'ud.rezeki@gmail.com',
    phone: '024-11223344',
    address: 'Jl. Pemuda No. 12, Semarang',
    status: 'inactive',
    bank_name: 'Bank BNI',
    account_number: '9998887777',
    account_name: 'Bapak Sutrisno',
    payment_term: '60 hari',
    created_at: '2024-01-25',
  },
];

export const items = [
  {
    id: 1,
    name: 'MAJUN',
    description: 'SERVO VALVE OLD MODEL . 0761-004MANEW MODEL . 0761-30348 TYPE : SPESIFIKASI MODEL : G122-829A001',
    category: 'Elektronik',
    unit: 'pcs',
    min_stock: 10,
    warranty: '6 bulan',
    photo_url: '/images/majun.jpg',
    created_at: '2024-01-10',
  },
  {
    id: 2,
    name: 'KUAS',
    description: 'Bearing BALL BEARING CONSOLIDATED BEARING COMPANY TYPE : B-1613',
    category: 'Tools',
    unit: 'pcs',
    min_stock: 20,
    warranty: '1 tahun',
    photo_url: '/images/kuas.jpg',
    created_at: '2024-01-12',
  },
  {
    id: 3,
    name: 'RELAY 4CH',
    description: 'SENSOR LEVEL MATERIAL : STAINLESS STEEL 316 L, MODEL : SPESIFIKASI : FLS SENSOR',
    category: 'Elektronik',
    unit: 'pcs',
    min_stock: 15,
    warranty: '6 bulan',
    photo_url: '/images/relay.jpg',
    created_at: '2024-02-05',
  },
  {
    id: 4,
    name: 'GERGAJI BESI',
    description: 'Gergaji untuk memotong besi dan metal',
    category: 'Tools',
    unit: 'pcs',
    warranty: '3 bulan',
    photo_url: '/images/gergaji.jpg',
    created_at: '2024-02-15',
  },
  {
    id: 5,
    name: 'TANG POTONG',
    description: 'Tang potong kabel heavy duty',
    category: 'Tools',
    unit: 'pcs',
    min_stock: 8,
    warranty: '1 tahun',
    photo_url: '/images/tang.jpg',
    created_at: '2024-03-01',
  },
  {
    id: 6,
    name: 'OBENG SET',
    description: 'Set obeng 12 pcs berbagai ukuran',
    category: 'Tools',
    unit: 'set',
    min_stock: 12,
    warranty: '6 bulan',
    photo_url: '/images/obeng.jpg',
    created_at: '2024-03-05',
  },
];

export const itemVendors = [
  { id: 1, item_id: 1, vendor_id: 1, vendor_item_name: 'MAJUN Premium', link_url: 'https://tokopedia.com/majun' },
  { id: 2, item_id: 1, vendor_id: 2, vendor_item_name: 'MAJUN Standard', link_url: 'https://shopee.co.id/majun' },
  { id: 3, item_id: 2, vendor_id: 1, vendor_item_name: 'KUAS A1', link_url: 'https://tokopedia.com/kuas' },
  { id: 4, item_id: 2, vendor_id: 3, vendor_item_name: 'KUAS Pro', link_url: '' },
  { id: 5, item_id: 3, vendor_id: 2, vendor_item_name: 'Relay 4 Channel', link_url: 'https://bukalapak.com/relay' },
  { id: 6, item_id: 4, vendor_id: 3, vendor_item_name: 'Gergaji Besi 12"', link_url: '' },
  { id: 7, item_id: 5, vendor_id: 1, vendor_item_name: 'Tang Potong Heavy', link_url: 'https://tokopedia.com/tang' },
  { id: 8, item_id: 6, vendor_id: 2, vendor_item_name: 'Obeng Set 12pcs', link_url: 'https://shopee.co.id/obeng' },
];

export const purchases = [
  {
    id: 1,
    user_id: 1,
    po_number: 'PO-2024-001',
    job_detail: 'Pengadaan MAJUN untuk proyek valve system',
    qty: 10,
    unit: 'EA',
    price_unit: 850000,
    price_shipping: 250000,
    price_admin: 50000,
    price_fee: 100000,
    price_total: 8900000,
    vendor_id: 1,
    payment_term: 'TRANSFER 30 hari',
    delivery_deadline: '2024-02-15',
    expedition: 'JNE Express',
    status: 'approved',
    created_at: '2024-01-20T10:30:00',
  },
  {
    id: 2,
    user_id: 2,
    po_number: 'PO-2024-002',
    job_detail: 'Pembelian KUAS untuk maintenance sistem hidrolik',
    qty: 5,
    unit: 'EA',
    price_unit: 1250000,
    price_shipping: 200000,
    price_admin: 50000,
    price_fee: 80000,
    price_total: 6580000,
    vendor_id: 2,
    payment_term: '30 hari',
    delivery_deadline: '2024-02-10',
    expedition: 'TIKI ONS',
    status: 'completed',
    created_at: '2024-01-25T14:20:00',
  },
  {
    id: 3,
    user_id: 1,
    po_number: 'PO-2024-003',
    job_detail: 'Supply RELAY 4CH untuk panel kontrol',
    qty: 20,
    unit: 'PCS',
    price_unit: 125000,
    price_shipping: 150000,
    price_admin: 25000,
    price_fee: 50000,
    price_total: 2725000,
    vendor_id: 2,
    payment_term: 'COD',
    delivery_deadline: '2024-03-01',
    expedition: 'Sicepat',
    status: 'pending',
    created_at: '2024-02-15T09:00:00',
  },
  {
    id: 4,
    user_id: 3,
    po_number: 'PO-2024-004',
    job_detail: 'Pengadaan GERGAJI BESI untuk workshop',
    qty: 15,
    unit: 'EA',
    price_unit: 175000,
    price_shipping: 100000,
    price_admin: 30000,
    price_fee: 40000,
    price_total: 2795000,
    vendor_id: 3,
    payment_term: '45 hari',
    delivery_deadline: '2024-03-20',
    expedition: 'JNE REG',
    status: 'approved',
    created_at: '2024-03-01T11:45:00',
  },
  {
    id: 5,
    user_id: 2,
    po_number: 'PO-2024-005',
    job_detail: 'Pembelian TANG POTONG untuk electrical team',
    qty: 8,
    unit: 'EA',
    price_unit: 320000,
    price_shipping: 80000,
    price_admin: 20000,
    price_fee: 30000,
    price_total: 2690000,
    vendor_id: 1,
    payment_term: 'TRANSFER 30 hari',
    delivery_deadline: '2024-04-10',
    expedition: 'JNE Express',
    status: 'completed',
    created_at: '2024-03-15T16:30:00',
  },
  {
    id: 6,
    user_id: 1,
    po_number: 'PO-2024-006',
    job_detail: 'Supply OBENG SET untuk maintenance',
    qty: 12,
    unit: 'SET',
    price_unit: 450000,
    price_shipping: 120000,
    price_admin: 35000,
    price_fee: 55000,
    price_total: 5610000,
    vendor_id: 2,
    payment_term: '30 hari',
    delivery_deadline: '2024-05-05',
    expedition: 'TIKI ONS',
    status: 'rejected',
    created_at: '2024-04-10T08:15:00',
  },
  {
    id: 7,
    user_id: 3,
    po_number: 'PO-2025-001',
    job_detail: 'Pengadaan MAJUN batch 2 untuk project expansion',
    qty: 25,
    unit: 'EA',
    price_unit: 820000,
    price_shipping: 400000,
    price_admin: 75000,
    price_fee: 150000,
    price_total: 21125000,
    vendor_id: 1,
    payment_term: 'TRANSFER 30 hari',
    delivery_deadline: '2025-02-28',
    expedition: 'JNE Express',
    status: 'approved',
    created_at: '2025-01-15T10:00:00',
  },
  {
    id: 8,
    user_id: 2,
    po_number: 'PO-2025-002',
    job_detail: 'Supply RELAY 4CH untuk upgrade system',
    qty: 50,
    unit: 'PCS',
    price_unit: 120000,
    price_shipping: 200000,
    price_admin: 50000,
    price_fee: 80000,
    price_total: 6330000,
    vendor_id: 2,
    payment_term: 'COD',
    delivery_deadline: '2025-03-15',
    expedition: 'Sicepat',
    status: 'pending',
    created_at: '2025-02-20T13:45:00',
  },
];

export const inquiries = [
  {
    id: 1,
    user_id: 1,
    vendor_id: 1,
    item_id: 1,
    vendor_item_name: 'MAJUN MERAH - Lap Kain Premium',
    link_url: 'https://tokopedia.com/elektronikjaya/majun-merah',
    subject: 'Pertanyaan Harga MAJUN',
    inquiry_date: '2024-01-10',
    message: 'Mohon info harga dan ketersediaan MAJUN untuk 10 unit',
    qty: 10,
    unit: 'EA',
    price_unit: 850000,
    price_total: 8500000,
    vendor_status: 'approved',
    reply_message: 'Harga Rp 850.000/unit. Stock tersedia 15 unit.',
    status: 'replied',
    created_at: '2024-01-10T09:00:00',
  },
  {
    id: 2,
    user_id: 2,
    vendor_id: 2,
    item_id: 2,
    vendor_item_name: 'KUAS CAT BESI - Brush Pro',
    link_url: 'https://shopee.co.id/majubersama/kuas-cat',
    subject: 'Diskon Pembelian KUAS',
    inquiry_date: '2024-01-18',
    message: 'Apakah ada diskon untuk pembelian KUAS minimal 5 unit?',
    qty: 5,
    unit: 'EA',
    price_unit: 45000,
    price_total: 225000,
    vendor_status: 'approved',
    reply_message: 'Ada diskon 10% untuk pembelian minimal 5 unit',
    status: 'closed',
    created_at: '2024-01-18T14:30:00',
  },
  {
    id: 3,
    user_id: 1,
    vendor_id: 2,
    item_id: 3,
    vendor_item_name: 'RELAY 4 CHANNEL 5V DC',
    link_url: 'https://bukalapak.com/majubersama/relay-4ch',
    subject: 'Lead Time RELAY 4CH',
    inquiry_date: '2024-02-05',
    message: 'Berapa lead time untuk RELAY 4CH 20 pcs?',
    qty: 20,
    unit: 'PCS',
    price_unit: 85000,
    price_total: 1700000,
    vendor_status: 'pending',
    status: 'sent',
    created_at: '2024-02-05T11:20:00',
  },
  {
    id: 4,
    user_id: 3,
    vendor_id: 3,
    item_id: 4,
    vendor_item_name: 'GERGAJI BESI HSS 12 inch',
    link_url: 'https://tokopedia.com/teknikmandiri/gergaji-besi',
    subject: 'Penawaran GERGAJI BESI',
    inquiry_date: '2024-02-20',
    message: 'Mohon penawaran untuk GERGAJI BESI 15 unit dengan garansi extended',
    qty: 15,
    unit: 'EA',
    price_unit: 125000,
    price_total: 1875000,
    vendor_status: 'approved',
    reply_message: 'Penawaran special Rp 125.000/unit dengan garansi 1 tahun',
    status: 'replied',
    created_at: '2024-02-20T10:15:00',
  },
  {
    id: 5,
    user_id: 2,
    vendor_id: 1,
    item_id: 5,
    vendor_item_name: 'TANG POTONG 8 inch Industrial',
    link_url: 'https://tokopedia.com/elektronikjaya/tang-potong',
    subject: 'Harga TANG POTONG',
    inquiry_date: '2024-03-05',
    message: 'Info harga TANG POTONG untuk 8 unit dengan expedisi express',
    qty: 8,
    unit: 'EA',
    price_unit: 175000,
    price_total: 1400000,
    vendor_status: 'approved',
    reply_message: 'Harga Rp 175.000/unit, expedisi express +Rp 50.000',
    status: 'closed',
    created_at: '2024-03-05T15:45:00',
  },
  {
    id: 6,
    user_id: 1,
    vendor_id: 2,
    item_id: 6,
    vendor_item_name: 'OBENG SET MAGNETIC 24 PCS',
    link_url: 'https://shopee.co.id/majubersama/obeng-set',
    subject: 'Stock OBENG SET',
    inquiry_date: '2024-03-25',
    message: 'Apakah OBENG SET tersedia ready stock? Butuh 12 set urgent',
    qty: 12,
    unit: 'SET',
    price_unit: 280000,
    price_total: 3360000,
    vendor_status: 'pending',
    status: 'sent',
    created_at: '2024-03-25T08:30:00',
  },
];

export const tenders = [
  {
    id: 1,
    user_id: 1,
    tender_date: '2024-01-05',
    letter_number: '001/KCK-BP/I/24',
    job_title: 'Jasa Perbaikan AC Ruang Server Utama',
    company_name: 'PT PLN NP UP KALTIM TELUK',
    status_po: 'KTC013',
    nominal_modal: 51688000,
    penawaran_exc: 0,
    spare_nego: 0,
    nominal_nego: 0,
    status_tender: 'menang_tender',
    nominal_pemenang: 51688000,
    notes: 'Proyek perbaikan AC untuk menjaga suhu optimal server',
    created_at: '2024-01-05',
  },
  {
    id: 2,
    user_id: 2,
    tender_date: '2024-02-15',
    letter_number: '002/KCK-BP/II/24',
    job_title: 'Kontrak Payung Service Rutin Gedung Perkantoran',
    company_name: 'PT PLN NP UP KALTIM TELUK',
    status_po: 'KTCP01',
    nominal_modal: 121366666,
    penawaran_exc: 0,
    spare_nego: 0,
    nominal_nego: 0,
    status_tender: 'menang_tender',
    nominal_pemenang: 121366666,
    notes: 'Kontrak payung untuk service maintenance selama 1 tahun',
    created_at: '2024-02-15',
  },
  {
    id: 3,
    user_id: 1,
    tender_date: '2024-03-20',
    letter_number: '003/KCK-BP/III/24',
    job_title: 'Pengadaan Connector Vibrasi untuk Mesin Produksi',
    company_name: 'PT PLN NP UP KALTIM TELUK',
    status_po: 'KTC015',
    nominal_modal: 21664980,
    penawaran_exc: 0,
    spare_nego: 0,
    nominal_nego: 0,
    status_tender: 'menang_tender',
    nominal_pemenang: 21664980,
    notes: 'Connector vibrasi untuk mengurangi getaran mesin',
    created_at: '2024-03-20',
  },
  {
    id: 4,
    user_id: 3,
    tender_date: '2024-04-10',
    letter_number: '004/KCK-BP/IV/24',
    job_title: 'Stock Consumable Material Workshop Tahunan',
    company_name: 'PT PLN NP UP KALTIM TELUK',
    status_po: 'KTC020',
    nominal_modal: 187445930,
    penawaran_exc: 0,
    spare_nego: 0,
    nominal_nego: 0,
    status_tender: 'kalah_tender',
    nominal_pemenang: 0,
    notes: 'Kalah tender karena harga tidak kompetitif',
    created_at: '2024-04-10',
  },
  {
    id: 5,
    user_id: 2,
    tender_date: '2024-05-15',
    letter_number: '005/KCK-BP/V/24',
    job_title: 'Pengadaan Material Cooling Tower System',
    company_name: 'PT PLN NP UP KALTIM TELUK',
    status_po: 'KTC025',
    nominal_modal: 95500000,
    penawaran_exc: 100000000,
    spare_nego: 2000000,
    nominal_nego: 98000000,
    status_tender: 'menang_tender',
    nominal_pemenang: 98000000,
    notes: 'Menang setelah negosiasi harga dengan spare nego 2jt',
    created_at: '2024-05-15',
  },
  {
    id: 6,
    user_id: 1,
    tender_date: '2024-06-20',
    letter_number: '006/KCK-BP/VI/24',
    job_title: 'Maintenance Sistem Elektrikal Gedung A & B',
    company_name: 'PT PLN NP UP KALTIM TELUK',
    status_po: 'KTCP05',
    nominal_modal: 75000000,
    penawaran_exc: 0,
    spare_nego: 0,
    nominal_nego: 0,
    status_tender: 'pending',
    nominal_pemenang: 0,
    notes: 'Menunggu hasil evaluasi tender dari client',
    created_at: '2024-06-20',
  },
  {
    id: 7,
    user_id: 3,
    tender_date: '2024-08-10',
    letter_number: '007/KCK-BP/VIII/24',
    job_title: 'Supply Spare Part Generator Set 500KVA',
    company_name: 'PT PLN NP UP KALTIM TELUK',
    status_po: 'KTC030',
    nominal_modal: 127500000,
    penawaran_exc: 135000000,
    spare_nego: 3500000,
    nominal_nego: 131500000,
    status_tender: 'menang_tender',
    nominal_pemenang: 131500000,
    notes: 'Menang tender dengan negosiasi spare 3.5jt',
    created_at: '2024-08-10',
  },
  {
    id: 8,
    user_id: 2,
    tender_date: '2024-10-05',
    letter_number: '008/KCK-BP/X/24',
    job_title: 'Upgrade Fire Detection System Seluruh Area',
    company_name: 'PT PLN NP UP KALTIM TELUK',
    status_po: 'KTC035',
    nominal_modal: 220000000,
    penawaran_exc: 0,
    spare_nego: 0,
    nominal_nego: 0,
    status_tender: 'kalah_tender',
    nominal_pemenang: 0,
    notes: 'Kalah tender, kompetitor menawarkan harga lebih rendah',
    created_at: '2024-10-05',
  },
];

// Helper functions
export const getVendorById = (id: number) => vendors.find(v => v.id === id);
export const getItemById = (id: number) => items.find(i => i.id === id);
export const getUserById = (id: number) => users.find(u => u.id === id);
export const getPurchaseById = (id: number) => purchases.find(p => p.id === id);
export const getInquiryById = (id: number) => inquiries.find(i => i.id === id);
export const getTenderById = (id: number) => tenders.find(t => t.id === id);

export const getItemsByVendor = (vendorId: number) => {
  const relations = itemVendors.filter(iv => iv.vendor_id === vendorId);
  return relations.map(rel => ({
    ...getItemById(rel.item_id)!,
    vendor_item_name: rel.vendor_item_name,
    link_url: rel.link_url,
  }));
};

export const getVendorsByItem = (itemId: number) => {
  const relations = itemVendors.filter(iv => iv.item_id === itemId);
  return relations.map(rel => ({
    ...getVendorById(rel.vendor_id)!,
    vendor_item_name: rel.vendor_item_name,
    link_url: rel.link_url,
  }));
};

// Statistics for Dashboard
export const getDashboardStats = () => {
  return {
    totalPurchases: purchases.length,
    totalTenders: tenders.length,
    totalVendors: vendors.filter(v => v.status === 'active').length,
    totalItems: items.length,
    purchaseByStatus: {
      pending: purchases.filter(p => p.status === 'pending').length,
      approved: purchases.filter(p => p.status === 'approved').length,
      rejected: purchases.filter(p => p.status === 'rejected').length,
      completed: purchases.filter(p => p.status === 'completed').length,
    },
    tenderByStatus: {
      menang_tender: tenders.filter(t => t.status_tender === 'menang_tender').length,
      kalah_tender: tenders.filter(t => t.status_tender === 'kalah_tender').length,
      pending: tenders.filter(t => t.status_tender === 'pending').length,
    },
  };
};

export const getMonthlyPurchaseTrend = () => {
  // Group purchases by month (last 6 months)
  const months = ['Jun 2025', 'Jul 2025', 'Agu 2025', 'Sep 2025', 'Okt 2025', 'Nov 2025'];
  return {
    labels: months,
    data: [8900000, 6580000, 90000000, 25000000, 15000000, 75000000], // Dummy monthly totals
  };
};

export const getTopVendors = () => {
  const vendorTotals = vendors.slice(0, 5).map((vendor, idx) => ({
    name: vendor.name,
    total: [25000000, 18000000, 12000000, 9000000, 6000000][idx],
  }));
  return vendorTotals;
};
